<?php

namespace Xuple\EvoLayer\Base\Support;

use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Route;
use RuntimeException;
use Symfony\Component\Yaml\Yaml;

class OntologyCompiler
{
    /**
     * Compile multiple ontology files from a registry, merging by declared namespace.
     *
     * Each registered file declares its own `namespace` (e.g. `evolayer.base`,
     * `evo.commerce`). The merged output is keyed by namespace, so sibling
     * packages can declare overlapping entity/event/block names without
     * collision — they're scoped under their own namespace.
     *
     * Throws if two registered sources declare the same namespace, or if a
     * file's declared `namespace` doesn't match its registered key.
     *
     * @return array<string, mixed>
     */
    public function compileAll(OntologyRegistry $registry, ?string $hostSource = null): array
    {
        $sources = $registry->all();

        if ($hostSource !== null) {
            if (! is_file($hostSource)) {
                throw new RuntimeException("Host ontology not found: {$hostSource}");
            }
            // A host ontology whose declared namespace matches a registered
            // package OVERRIDES that package's copy — this is how a host
            // customises e.g. evolayer.base after publishing it. A novel namespace
            // (typically "app") is merged additively.
            $hostNamespace = $this->declaredNamespace($hostSource) ?? 'app';
            $sources[$hostNamespace] = $hostSource;
        }

        if (empty($sources)) {
            throw new RuntimeException(
                'No ontology sources registered. Either call OntologyRegistry::register() '.
                'from a service provider, or pass --source= explicitly.'
            );
        }

        $compiled = [];
        foreach ($sources as $namespace => $path) {
            $compiled[$namespace] = $this->compile($path);
        }

        return [
            'compiled_at' => now()->toISOString(),
            'namespaces' => $compiled,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function compile(string $sourcePath): array
    {
        if (! is_file($sourcePath)) {
            throw new RuntimeException("Ontology source not found: {$sourcePath}");
        }

        $ontology = Yaml::parseFile($sourcePath);

        if (! is_array($ontology)) {
            throw new RuntimeException('Ontology source must parse to a YAML mapping.');
        }

        $warnings = $this->validate($ontology);

        return [
            'compiled_at' => now()->toISOString(),
            'source' => [
                'path' => $sourcePath,
                'sha256' => hash_file('sha256', $sourcePath),
            ],
            'version' => $ontology['version'],
            'namespace' => $ontology['namespace'],
            'ontology' => $ontology,
            'indexes' => $this->indexes($ontology),
            'warnings' => $warnings,
        ];
    }

    /**
     * @param  array<string, mixed>  $compiled
     */
    public function toTypeScript(array $compiled): string
    {
        // Merged (multi-namespace) shape: emit a namespace-keyed map. Per-entity
        // derived types don't generalise across namespaces, so we expose a
        // namespace key type instead.
        if (isset($compiled['namespaces'])) {
            $byNamespace = [];
            $indexesByNamespace = [];
            foreach ($compiled['namespaces'] as $namespace => $ns) {
                $byNamespace[$namespace] = $ns['ontology'];
                $indexesByNamespace[$namespace] = $ns['indexes'];
            }

            $ontologyJson = $this->toPrettyTypeScriptJson($byNamespace);
            $indexesJson = $this->toPrettyTypeScriptJson($indexesByNamespace);

            return <<<TS
// Generated by php artisan evolayer:ontology:compile. Merged across all registered namespaces.

export const ontology = {$ontologyJson} as const;

export const ontologyIndexes = {$indexesJson} as const;

export type Ontology = typeof ontology;
export type OntologyIndexes = typeof ontologyIndexes;
export type OntologyNamespace = keyof Ontology;

TS;
        }

        $ontology = $this->toPrettyTypeScriptJson($compiled['ontology']);
        $indexes = $this->toPrettyTypeScriptJson($compiled['indexes']);

        return <<<TS
// Generated by php artisan evolayer:ontology:compile.

export const ontology = {$ontology} as const;

export const ontologyIndexes = {$indexes} as const;

export type Ontology = typeof ontology;
export type OntologyIndexes = typeof ontologyIndexes;
export type OntologyEntity = keyof Ontology['entities'];
export type OntologyEvent = keyof Ontology['events'];
export type OntologyJob = keyof Ontology['jobs'];
export type OntologyAgent = keyof Ontology['agents'];
export type OntologyBlock = keyof Ontology['blocks'];
export type OntologyProjection = keyof Ontology['projections'];
export type OntologyLane = keyof Ontology['lanes'];
export type OntologyTable = keyof OntologyIndexes['entities_by_table'];
export type OntologyRoute = keyof OntologyIndexes['projections_by_route'];
export type OntologyEndpoint = keyof OntologyIndexes['blocks_by_endpoint'];
export type SemanticSearchStrategy = Ontology['lanes'][OntologyLane]['semantic_search_strategy'];

TS;
    }

    /**
     * @param  array<string, mixed>  $compiled
     */
    public function toMermaidErd(array $compiled): string
    {
        // Merged shape: concatenate each namespace's ERD under a comment header.
        if (isset($compiled['namespaces'])) {
            $sections = [];
            foreach ($compiled['namespaces'] as $namespace => $ns) {
                $sections[] = "%% namespace: {$namespace}\n".$this->toMermaidErd($ns);
            }

            return implode("\n\n", $sections);
        }

        $ontology = $compiled['ontology'];
        $entities = $this->arrayAt($ontology, 'entities');
        $tableNames = [];

        foreach ($entities as $entityName => $entity) {
            if (is_array($entity) && isset($entity['table']) && is_string($entity['table'])) {
                $tableNames[$entityName] = $entity['table'];
            }
        }

        $lines = ['erDiagram'];

        foreach ($tableNames as $entityName => $tableName) {
            $entity = $entities[$entityName];
            $lines[] = "    {$this->erdIdentifier($tableName)} {";

            foreach ((array) ($entity['fields'] ?? []) as $fieldName => $field) {
                $suffix = $fieldName === ($entity['key'] ?? null) ? ' PK' : '';
                $lines[] = sprintf(
                    '        %s %s%s',
                    $this->erdFieldType($field),
                    $this->erdIdentifier((string) $fieldName),
                    $suffix,
                );
            }

            $lines[] = '    }';
        }

        foreach ($tableNames as $entityName => $tableName) {
            $entity = $entities[$entityName];

            foreach ((array) ($entity['relations'] ?? []) as $relationName => $relation) {
                if (! is_array($relation)) {
                    continue;
                }

                $target = $relation['target'] ?? null;
                $type = $relation['type'] ?? null;

                if (! is_string($target) || ! is_string($type) || ! isset($tableNames[$target])) {
                    continue;
                }

                $from = $this->erdIdentifier($tableName);
                $to = $this->erdIdentifier($tableNames[$target]);
                $label = $this->erdIdentifier((string) $relationName);

                $lines[] = match ($type) {
                    'belongs_to' => "    {$to} ||--o{ {$from} : {$label}",
                    'has_many', 'morph_many' => "    {$from} ||--o{ {$to} : {$label}",
                    'morph_to_many' => "    {$from} }o--o{ {$to} : {$label}",
                    default => "    {$from} ||--|| {$to} : {$label}",
                };
            }
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /**
     * @param  array<string, mixed>  $ontology
     */
    private function declaredNamespace(string $path): ?string
    {
        $parsed = Yaml::parseFile($path);

        return is_array($parsed) && isset($parsed['namespace']) && is_string($parsed['namespace'])
            ? $parsed['namespace']
            : null;
    }

    /**
     * Validate the ontology in two tiers:
     *
     *  - Structural integrity (HARD — throws): required keys, entity/event/
     *    workflow cross-references, and PHP class existence. Classes are always
     *    autoloaded regardless of which features are toggled, so a missing
     *    class is a genuine authoring error.
     *
     *  - Environmental references (SOFT — collected as warnings): route and
     *    block-file existence. These depend on the host's enabled feature
     *    flags and which frontend tags have been published — a disabled
     *    feature legitimately has no registered route or published block file.
     *    The ontology describes the full design surface, so we report these as
     *    advisories rather than failing the compile.
     *
     * @return list<string> advisory warnings
     */
    private function validate(array $ontology): array
    {
        $warnings = [];

        foreach (['version', 'namespace', 'entities', 'events', 'jobs', 'blocks'] as $key) {
            if (! array_key_exists($key, $ontology)) {
                throw new RuntimeException("Ontology is missing required key: {$key}");
            }
        }

        $entities = $this->arrayAt($ontology, 'entities');
        $events = $this->arrayAt($ontology, 'events');
        $jobs = $this->arrayAt($ontology, 'jobs');
        $blocks = $this->arrayAt($ontology, 'blocks');
        $agents = $this->arrayAt($ontology, 'agents');

        $entityNames = array_keys($entities);
        $eventNames = array_keys($events);
        $jobNames = array_keys($jobs);

        foreach ($entities as $entityName => $entity) {
            if (! is_array($entity)) {
                throw new RuntimeException("Entity [{$entityName}] must be a mapping.");
            }

            $this->validateRelations($entityName, $entity, $entityNames);
            $this->validateWorkflows($entityName, $entity, $eventNames, $jobNames);
        }

        foreach ($events as $eventName => $event) {
            if (! is_array($event)) {
                throw new RuntimeException("Event [{$eventName}] must be a mapping.");
            }

            $subject = $event['subject'] ?? null;
            if (is_string($subject) && ! in_array($subject, $entityNames, true)) {
                throw new RuntimeException("Event [{$eventName}] references unknown subject entity [{$subject}].");
            }
        }

        foreach ($jobs as $jobName => $job) {
            if (! is_array($job)) {
                throw new RuntimeException("Job [{$jobName}] must be a mapping.");
            }

            $class = $job['class'] ?? null;
            if (is_string($class) && ! class_exists($class)) {
                throw new RuntimeException("Job [{$jobName}] references missing class [{$class}].");
            }
        }

        foreach ($agents as $agentName => $agent) {
            if (! is_array($agent)) {
                throw new RuntimeException("Agent [{$agentName}] must be a mapping.");
            }

            $class = $agent['class'] ?? null;
            if (is_string($class) && ! class_exists($class)) {
                throw new RuntimeException("Agent [{$agentName}] references missing class [{$class}].");
            }

            $endpoint = $agent['endpoint'] ?? null;
            if (is_string($endpoint) && ! Route::has($endpoint)) {
                $warnings[] = "Agent [{$agentName}] endpoint route [{$endpoint}] is not registered (feature likely disabled).";
            }
        }

        foreach ($blocks as $blockName => $block) {
            if (! is_array($block)) {
                throw new RuntimeException("Block [{$blockName}] must be a mapping.");
            }

            $path = $block['path'] ?? null;
            if (is_string($path) && ! is_file(base_path($path))) {
                $warnings[] = "Block [{$blockName}] path [{$path}] is not present (frontend likely not published).";
            }

            $endpoint = $block['endpoint'] ?? null;
            if (is_string($endpoint) && ! Route::has($endpoint)) {
                $warnings[] = "Block [{$blockName}] endpoint route [{$endpoint}] is not registered (feature likely disabled).";
            }
        }

        foreach ($this->arrayAt($ontology, 'projections') as $projectionName => $projection) {
            if (! is_array($projection)) {
                throw new RuntimeException("Projection [{$projectionName}] must be a mapping.");
            }

            $route = $projection['route'] ?? null;
            if (is_string($route) && ! Route::has($route)) {
                $warnings[] = "Projection [{$projectionName}] route [{$route}] is not registered (feature likely disabled).";
            }
        }

        return $warnings;
    }

    /**
     * @param  array<string, mixed>  $entity
     * @param  list<string>  $entityNames
     */
    private function validateRelations(string $entityName, array $entity, array $entityNames): void
    {
        foreach ((array) ($entity['relations'] ?? []) as $relationName => $relation) {
            if (! is_array($relation)) {
                throw new RuntimeException("Relation [{$entityName}.{$relationName}] must be a mapping.");
            }

            $target = $relation['target'] ?? null;
            if (is_string($target) && $target !== 'any' && ! in_array($target, $entityNames, true)) {
                throw new RuntimeException("Relation [{$entityName}.{$relationName}] references unknown target [{$target}].");
            }
        }
    }

    /**
     * @param  array<string, mixed>  $entity
     * @param  list<string>  $eventNames
     * @param  list<string>  $jobNames
     */
    private function validateWorkflows(string $entityName, array $entity, array $eventNames, array $jobNames): void
    {
        foreach ((array) ($entity['workflows'] ?? []) as $workflowName => $workflow) {
            if (! is_array($workflow)) {
                throw new RuntimeException("Workflow [{$entityName}.{$workflowName}] must be a mapping.");
            }

            foreach ((array) ($workflow['emits'] ?? []) as $eventName) {
                if (! is_string($eventName) || ! in_array($eventName, $eventNames, true)) {
                    throw new RuntimeException("Workflow [{$entityName}.{$workflowName}] emits unknown event [{$eventName}].");
                }
            }

            foreach ((array) ($workflow['dispatches'] ?? []) as $jobName) {
                if (! is_string($jobName) || ! in_array($jobName, $jobNames, true)) {
                    throw new RuntimeException("Workflow [{$entityName}.{$workflowName}] dispatches unknown job [{$jobName}].");
                }
            }
        }
    }

    /**
     * @param  array<string, mixed>  $ontology
     * @return array<string, array<string, mixed>>
     */
    private function indexes(array $ontology): array
    {
        $entitiesByTable = [];
        $entitiesByModel = [];
        foreach ($this->arrayAt($ontology, 'entities') as $entityName => $entity) {
            if (! is_array($entity)) {
                continue;
            }

            if (isset($entity['table']) && is_string($entity['table'])) {
                $entitiesByTable[$entity['table']] = $entityName;
            }

            if (isset($entity['model']) && is_string($entity['model'])) {
                $entitiesByModel[$entity['model']] = $entityName;
            }
        }

        $eventsBySubject = [];
        foreach ($this->arrayAt($ontology, 'events') as $eventName => $event) {
            $subject = is_array($event) ? ($event['subject'] ?? null) : null;
            if (is_string($subject)) {
                $eventsBySubject[$subject][] = $eventName;
            }
        }

        $blocksByEndpoint = [];
        foreach ($this->arrayAt($ontology, 'blocks') as $blockName => $block) {
            $endpoint = is_array($block) ? ($block['endpoint'] ?? null) : null;
            if (is_string($endpoint)) {
                $blocksByEndpoint[$endpoint] = $blockName;
            }
        }

        $agentsByEndpoint = [];
        foreach ($this->arrayAt($ontology, 'agents') as $agentName => $agent) {
            $endpoint = is_array($agent) ? ($agent['endpoint'] ?? null) : null;
            if (is_string($endpoint)) {
                $agentsByEndpoint[$endpoint] = $agentName;
            }
        }

        $projectionsByRoute = [];
        foreach ($this->arrayAt($ontology, 'projections') as $projectionName => $projection) {
            $route = is_array($projection) ? ($projection['route'] ?? null) : null;
            if (is_string($route)) {
                $projectionsByRoute[$route] = $projectionName;
            }
        }

        return [
            'entities_by_table' => $entitiesByTable,
            'entities_by_model' => $entitiesByModel,
            'events_by_subject' => $eventsBySubject,
            'blocks_by_endpoint' => $blocksByEndpoint,
            'agents_by_endpoint' => $agentsByEndpoint,
            'projections_by_route' => $projectionsByRoute,
        ];
    }

    /**
     * @param  array<string, mixed>  $data
     * @return array<string, mixed>
     */
    private function arrayAt(array $data, string $key): array
    {
        $value = Arr::get($data, $key, []);

        if (! is_array($value)) {
            throw new RuntimeException("Ontology key [{$key}] must be a mapping.");
        }

        return $value;
    }

    private function erdIdentifier(string $value): string
    {
        return strtoupper((string) preg_replace('/[^A-Za-z0-9_]+/', '_', $value));
    }

    private function erdFieldType(mixed $field): string
    {
        if (is_string($field)) {
            return str_replace(['?', '(', ')'], '', $field);
        }

        if (! is_array($field)) {
            return 'string';
        }

        if (array_key_exists('enum', $field) || array_key_exists('enum?', $field)) {
            return 'enum';
        }

        if (array_key_exists('sqlite', $field) || array_key_exists('postgresql', $field)) {
            return 'lane_specific';
        }

        return 'json';
    }

    private function toPrettyTypeScriptJson(mixed $value): string
    {
        $json = json_encode(
            $value,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR,
        );

        return (string) preg_replace_callback(
            '/^( +)/m',
            fn (array $matches): string => str_repeat(' ', intdiv(strlen($matches[1]), 2)),
            $json,
        );
    }
}
